### ISSUE TITLE
precision_score.pkl not included

### ISSUE THREAD

**Issue by xiyaofu** [gujiuxiang/MIL.pytorch#1]
The precision_score.pkl is not included in the BaiduPan url. Could you please update it? @gujiuxiang

**Comment by gujiuxiang** [comment]
Hi, you can generate it with the code (in test.py).

if len(opt.load_precision_score) >0 :
    precision_score = pickle.load(open(opt.load_precision_score, 'rb'))
else:
    precision_score = compute_precision_mapping(pt)

**Comment by xiyaofu** [comment]
@gujiuxiang Thank you! This issue can be closed now.

**Comment by liuxx2016** [comment]
hello, when i run test.py,  I get an error “no such file or directory: 'model/precision_score.pkl '”. How can i solve it? thanks
